apiVersion: v1
kind: ConfigMap
metadata:
  name: user-portal-config
data:
  database-url: "postgresql://postgres:postgres@postgres:5432/user_portal"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-portal-secrets
type: Opaque
data:
  # Note: These are example values. In production, use proper secrets management
  session-secret: c2VjcmV0LWtleS1iYXNlNjQ= # base64 encoded
