apiVersion: v1
kind: Service
metadata:
  name: user-portal-backend
spec:
  selector:
    app: user-portal-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
