apiVersion: v1
kind: Service
metadata:
  name: user-portal-frontend
spec:
  selector:
    app: user-portal-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30001
  type: NodePort
